name: Compile and publish libnvram

on:
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true

      - name: Build 
        run: |
          docker run --rm -v $PWD:/app -w /app ghcr.io/rehosting/embedded-toolchains:latest /app/package.sh

      - name: Save package
        uses: actions/upload-artifact@v4.6.2
        with:
          name: libnvram-latest.tar.gz
          path: libnvram-latest.tar.gz

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.v-version }}${{ github.ref == 'refs/head/stable' && '-stable' || '' }}
          release_name: Release ${{ steps.version.outputs.v-version }} ${{ github.ref }}
          body: |
            Release ${{ steps.version.outputs.v-version }} @${{ github.ref }}
          draft: true
          prerelease: false
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./libnvram-latest.tar.gz
          asset_name: libnvram-latest.tar.gz
          asset_content_type: application/gzip

      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
